//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCasos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int IdProducto { get; set; }
        public string Tamano { get; set; }
        public string Diametro { get; set; }
        public Nullable<byte> Cantidad { get; set; }
        public byte IdColor { get; set; }
        public byte IdMarca { get; set; }
        public byte IdTipoProducto { get; set; }
        public string Comentario { get; set; }
        public int IdCaso { get; set; }
    }
}
